### ISSUE TITLE
MetroLogPage Shows FontManager Exception

### ISSUE THREAD

**Issue by Cruik** [roubachof/MetroLog#16]
Hey, when i am click on the RefreshCommand, im getting the following error message shown

`FontManager|Unable to load font 'sans-serif-medium' from assets. --> Java.Lang.RuntimeException: Font asset not found sans-serif-medium
   at Java.Interop.JniEnvironment.StaticMethods.CallStaticObjectMethod(JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:line 12890
   at Java.Interop.JniPeerMembers.JniStaticMethods.InvokeObjectMethod(String encodedMember, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs:line 95
   at Android.Graphics.Typeface.CreateFromAsset(AssetManager mgr, String path) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net6.0/android-33/mcw/Android.Graphics.Typeface.cs:line 613
   at Microsoft.Maui.FontManager.LoadTypefaceFromAsset(String fontfamily, Boolean warning) in D:\a\_work\1\s\src\Core\src\Fonts\FontManager.Android.cs:line 122
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Font asset not found sans-serif-medium
	at android.graphics.Typeface.createFromAsset(Typeface.java:839)
	at crc640ec207abc449b2ca.ShellFlyoutRecyclerAdapter.n_onBindViewHolder(Native Method)
	at crc640ec207abc449b2ca.ShellFlyoutRecyclerAdapter.onBindViewHolder(ShellFlyoutRecyclerAdapter.java:57)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7254)
....`

I added the specific .ttf but still get this exception shown, any ideas?

**Comment by roubachof** [comment]
looks like an internal maui issue. Try to open it on the maui github repo
