### ISSUE TITLE
MAUI HTTPClient.PostAsync call throws "BeginScope is not supported on MetroLog"

### ISSUE THREAD

**Issue by ac-c2it** [roubachof/MetroLog#6]
Followed your setup.  Calls to ILogger.LogInformation work as expected.  I get two inner exceptions from my line of 

`HttpResponseMessage result = await httpClient
                    .PostAsync($"api/Channels/get_channelgroup", content);`

"An error occurred while writing to logger(s). (BeginScope is not supported on MetroLog) (BeginScope is not supported on MetroLog)"

**Comment by ac-c2it** [comment]
Stack trace:
``  at MetroLog.MicrosoftExtensions.MicrosoftLoggerWrapper.BeginScope[LogValues`2](LogValues`2 state)
   at Microsoft.Extensions.Logging.ScopeLogger.CreateScope[LogValues`2](LogValues`2 state)
   at Microsoft.Extensions.Logging.Logger.BeginScope[LogValues`2](LogValues`2 state)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass2_0`2[[System.Net.Http.HttpMethod, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<DefineScope>b__0(ILogger logger, HttpMethod arg1, String arg2)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.Log.BeginRequestPipelineScope(ILogger logger, HttpRequestMessage request)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
``

**Comment by ac-c2it** [comment]
I found a work around.  I put             
`Services.RemoveAll<IHttpMessageHandlerBuilderFilter>();` 
after the creation of my httpclients.

**Comment by BaumTom** [comment]
I would suggest to use following implementation instead of throwing an `NotSupportedException`:

`    public IDisposable BeginScope<TState>(TState state)
    {
        return null;
    }`

I've just tried this and the httpClient has no issue with the `null` value. Dispose is only called on non `null` values.

**Comment by roubachof** [comment]
@BaumTom good point, would you make a pr for this one ?

**Comment by roubachof** [comment]
It will also fix #10
